name: ten_sports
description: A new Flutter application.

publish_to: 'none'

version: 1.0.7+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  better_player: ^0.0.37
  cloud_firestore:
  carousel_pro: ^1.0.0
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  package_info: ^0.4.3+2
  shared_preferences: ^0.5.12+4
#  google_fonts: ^1.1.1
#  firebase_admob: ^0.10.3




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/


  fonts:

    - family: normal
      fonts:
        - asset: fonts/normal.ttf

    - family: bold
      fonts:
        - asset: fonts/bold.ttf

